#########################################################################
###################### CerebralCortex Core Config #######################
#########################################################################
cc:
  debug: True # Setting this to True will log and print errors on console as well
  throw_exception: True #if this is set to True then application will get exceptions
  auth_token_expire_time: 40000 #seconds
  auth_encryption_key: "md@k&#8"
  log_files_path: "/tmp/"

#########################################################################
#                        NoSQL Storage                                  #
#########################################################################
nosql_storage: filesystem

filesystem:
  # in case of nosql_store=filesystem, provide directory path where all processed-data shall be stored
  filesystem_path: "/tmp/"

#hdfs:
#  host: localhost
#  port: 9001
#  raw_files_dir: "/cc3/"



#########################################################################
#                          Relational Storage                           #
#########################################################################
relational_storage: sqlite

sqlite:
  file_path: "/tmp/"

#mysql:
#  host: 127.0.0.1 # change if MySQL is installed remotely
#  port: 3306 # Change if MySQL is not using default port
#  db_user: root # Change
#  db_pass: pass # Change
#  database: cerebralcortex

#########################################################################
###################### Visualization Data Storage #######################
#########################################################################
visualization_storage: none

#influxdb:
#  host: 127.0.0.1
#  port: 8086
#  database: cerebralcortex_raw
#  db_user: ""
#  db_pass: ""

#########################################################################
#                          Data Provenance Storage                      #
#########################################################################
mprov: none

#pennprov:
#  host: http://127.0.0.1:8088
#  user: demo
#  password: demo
